import type { DeckMode, WordSource } from "../shared/types";

const COMMON_WORDS = [
  "Airplane",
  "Airport",
  "Anchor",
  "Apple",
  "Apron",
  "Aquarium",
  "Astronaut",
  "Backpack",
  "Bakery",
  "Balcony",
  "Balloon",
  "Banana",
  "Banjo",
  "Barbecue",
  "Baseball",
  "Basket",
  "Battery",
  "Beach",
  "Beehive",
  "Bell",
  "Belt",
  "Bench",
  "Bicycle",
  "Binoculars",
  "Biscuit",
  "Blanket",
  "Blender",
  "Blueprint",
  "Boat",
  "Bonfire",
  "Bookmark",
  "Bookstore",
  "Boots",
  "Bottle",
  "Bouquet",
  "Bowling",
  "Bracelet",
  "Bridge",
  "Broom",
  "Bubble",
  "Bucket",
  "Bus",
  "Cabin",
  "Cactus",
  "Calculator",
  "Calendar",
  "Camera",
  "Candle",
  "Canary",
  "Canoe",
  "Carnival",
  "Carpet",
  "Chair",
  "Chalkboard",
  "Chessboard",
  "Chocolate",
  "Circus",
  "Clock",
  "Closet",
  "Cloud",
  "Coffee",
  "Compass",
  "Concert",
  "Cookie",
  "Cornfield",
  "Costume",
  "Couch",
  "Crayon",
  "Cupcake",
  "Curtain",
  "Diamond",
  "Dinosaur",
  "Doorbell",
  "Donut",
  "Drum",
  "Elevator",
  "Envelope",
  "Factory",
  "Feather",
  "Ferry",
  "Fireplace",
  "Firework",
  "Flashlight",
  "Fountain",
  "Frisbee",
  "Garden",
  "Glacier",
  "Glasses",
  "Glove",
  "Guitar",
  "Hammock",
  "Harbor",
  "Harmonica",
  "Hat",
  "Helmet",
  "Highway",
  "Honey",
  "Iceberg",
  "Island",
  "Jacket",
  "Jellyfish",
  "Journal",
  "Kettle",
  "Keyhole",
  "Kite",
  "Kitchen",
  "Ladder",
  "Lantern",
  "Lemonade",
  "Library",
  "Lighthouse",
  "Lightning",
  "Lunchbox",
  "Magnet",
  "Mailbox",
  "Market",
  "Meadow",
  "Microscope",
  "Mirror",
  "Mittens",
  "Mountain",
  "Museum",
  "Necklace",
  "Notebook",
  "Ocean",
  "Orchestra",
  "Painter",
  "Parachute",
  "Park",
  "Passport",
  "Peanut",
  "Penguin",
  "Piano",
  "Picnic",
  "Pillow",
  "Pizza",
  "Planet",
  "Playground",
  "Pocket",
  "Popcorn",
  "Postcard",
  "Puzzle",
  "Racecar",
  "Radio",
  "Raincoat",
  "Rainbow",
  "Recipe",
  "Refrigerator",
  "River",
  "Robot",
  "Rocket",
  "Rollercoaster",
  "Saddle",
  "Sandbox",
  "Sandwich",
  "Saxophone",
  "Scarf",
  "School",
  "Scissors",
  "Seashell",
  "Shadow",
  "Shipwreck",
  "Skateboard",
  "Skyscraper",
  "Snowman",
  "Soap",
  "Soccer",
  "Spoon",
  "Stadium",
  "Starfish",
  "Statue",
  "Submarine",
  "Suitcase",
  "Sunglasses",
  "Surfboard",
  "Telescope",
  "Tent",
  "Theater",
  "Thunder",
  "Toaster",
  "Toolbox",
  "Toothbrush",
  "Tornado",
  "Treasure",
  "Treehouse",
  "Trumpet",
  "Umbrella",
  "Vacuum",
  "Violin",
  "Volcano",
  "Wallet",
  "Waterfall",
  "Wheelbarrow",
  "Whistle",
  "Windmill",
  "Window",
  "Xylophone",
  "Yacht",
  "Yo-Yo",
  "Zipper"
];

const ARCANE_WORDS = [
  "Abyss",
  "Acolyte",
  "Alchemist",
  "Amulet",
  "Archmage",
  "Armory",
  "Artifact",
  "Astral",
  "Banshee",
  "Bard",
  "Barrow",
  "Basilisk",
  "Bastion",
  "Battleaxe",
  "Battlement",
  "Beholder",
  "Blacksmith",
  "Bloodstone",
  "Bone Golem",
  "Brimstone",
  "Broadsword",
  "Catacomb",
  "Cauldron",
  "Cerberus",
  "Chainmail",
  "Changeling",
  "Chimera",
  "Cleric",
  "Cloak",
  "Coven",
  "Crown",
  "Crypt",
  "Crystal",
  "Cursed Idol",
  "Cyclops",
  "Dagger",
  "Djinn",
  "Doppelganger",
  "Dragon",
  "Druid",
  "Dryad",
  "Dungeon",
  "Dwarven Forge",
  "Eldritch",
  "Elemental",
  "Elixir",
  "Enchanter",
  "Ent",
  "Familiar",
  "Fey",
  "Fireball",
  "Gargoyle",
  "Gauntlet",
  "Genie",
  "Ghost",
  "Ghoul",
  "Giant",
  "Goblin",
  "Golem",
  "Griffin",
  "Grimoire",
  "Halberd",
  "Harpy",
  "Haunted Mirror",
  "Hellhound",
  "Hex",
  "Homunculus",
  "Hydra",
  "Illusion",
  "Imp",
  "Incantation",
  "Iron Gate",
  "Jester",
  "Kobold",
  "Kraken",
  "Labyrinth",
  "Leviathan",
  "Lich",
  "Longbow",
  "Lycanthrope",
  "Mage",
  "Mage Tower",
  "Mana",
  "Manticore",
  "Mermaid",
  "Mimic",
  "Minotaur",
  "Moon Gate",
  "Moonstone",
  "Necromancer",
  "Nightshade",
  "Obelisk",
  "Ogre",
  "Oracle",
  "Orc",
  "Paladin",
  "Pegasus",
  "Phylactery",
  "Phoenix",
  "Pixie",
  "Pixie Dust",
  "Portal",
  "Potion",
  "Priestess",
  "Prophecy",
  "Quest",
  "Rat King",
  "Raven",
  "Relic",
  "Revenant",
  "Riddle",
  "Rogue",
  "Rune",
  "Runestone",
  "Satyr",
  "Scepter",
  "Scroll",
  "Seer",
  "Sentinel",
  "Shapeshifter",
  "Shield",
  "Shrine",
  "Sigil",
  "Siren",
  "Slime",
  "Sorcerer",
  "Soul Gem",
  "Specter",
  "Spellbook",
  "Sphinx",
  "Spider Queen",
  "Spirit",
  "Staff",
  "Stone Circle",
  "Summoner",
  "Sword",
  "Talisman",
  "Tavern",
  "Thorn Crown",
  "Throne",
  "Tomb",
  "Torch",
  "Treasure Map",
  "Troll",
  "Unicorn",
  "Valkyrie",
  "Vampire",
  "Wand",
  "Warhammer",
  "Warlock",
  "Werewolf",
  "Witch",
  "Wizard",
  "Wraith",
  "Wyvern"
];

export function deckForMode(mode: DeckMode, wordSource: WordSource = "built-in", customWords: string[] = []) {
  const builtIn = builtInDeck(mode);
  if (wordSource === "custom") return [...customWords];
  if (wordSource === "combined") return uniqueWords([...builtIn, ...customWords]);
  return builtIn;
}

function builtInDeck(mode: DeckMode) {
  if (mode === "common") return [...COMMON_WORDS];
  if (mode === "arcane") return [...ARCANE_WORDS];
  return [...COMMON_WORDS, ...ARCANE_WORDS];
}

function uniqueWords(words: string[]) {
  const seen = new Set<string>();
  const unique: string[] = [];
  for (const word of words) {
    const key = word.toLocaleLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    unique.push(word);
  }
  return unique;
}
